version: "3.9"

services:
  nodeserver:
    image: node
    container_name: projectnode
    ports:
      - 5000:3000
    build: .
    command: npm run start
  db:
    image: mongo
    container_name: mymongo
    ports:
      - 27017:27017
